package com.reshape.app.db.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.reshape.app.db.entity.VideoEntity;
import com.reshape.app.db.entity.SearchItemEntity;

import com.reshape.app.db.entity.VideoEntityDao;
import com.reshape.app.db.entity.SearchItemEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoEntityDaoConfig;
    private final DaoConfig searchItemEntityDaoConfig;

    private final VideoEntityDao videoEntityDao;
    private final SearchItemEntityDao searchItemEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoEntityDaoConfig = daoConfigMap.get(VideoEntityDao.class).clone();
        videoEntityDaoConfig.initIdentityScope(type);

        searchItemEntityDaoConfig = daoConfigMap.get(SearchItemEntityDao.class).clone();
        searchItemEntityDaoConfig.initIdentityScope(type);

        videoEntityDao = new VideoEntityDao(videoEntityDaoConfig, this);
        searchItemEntityDao = new SearchItemEntityDao(searchItemEntityDaoConfig, this);

        registerDao(VideoEntity.class, videoEntityDao);
        registerDao(SearchItemEntity.class, searchItemEntityDao);
    }
    
    public void clear() {
        videoEntityDaoConfig.clearIdentityScope();
        searchItemEntityDaoConfig.clearIdentityScope();
    }

    public VideoEntityDao getVideoEntityDao() {
        return videoEntityDao;
    }

    public SearchItemEntityDao getSearchItemEntityDao() {
        return searchItemEntityDao;
    }

}
