package com.baogetv.app.db.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.baogetv.app.db.entity.VideoEntity;
import com.baogetv.app.db.entity.SearchItemEntity;
import com.baogetv.app.db.entity.HistoryItemEntity;
import com.baogetv.app.db.entity.UserItemEntity;

import com.baogetv.app.db.entity.VideoEntityDao;
import com.baogetv.app.db.entity.SearchItemEntityDao;
import com.baogetv.app.db.entity.HistoryItemEntityDao;
import com.baogetv.app.db.entity.UserItemEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoEntityDaoConfig;
    private final DaoConfig searchItemEntityDaoConfig;
    private final DaoConfig historyItemEntityDaoConfig;
    private final DaoConfig userItemEntityDaoConfig;

    private final VideoEntityDao videoEntityDao;
    private final SearchItemEntityDao searchItemEntityDao;
    private final HistoryItemEntityDao historyItemEntityDao;
    private final UserItemEntityDao userItemEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoEntityDaoConfig = daoConfigMap.get(VideoEntityDao.class).clone();
        videoEntityDaoConfig.initIdentityScope(type);

        searchItemEntityDaoConfig = daoConfigMap.get(SearchItemEntityDao.class).clone();
        searchItemEntityDaoConfig.initIdentityScope(type);

        historyItemEntityDaoConfig = daoConfigMap.get(HistoryItemEntityDao.class).clone();
        historyItemEntityDaoConfig.initIdentityScope(type);

        userItemEntityDaoConfig = daoConfigMap.get(UserItemEntityDao.class).clone();
        userItemEntityDaoConfig.initIdentityScope(type);

        videoEntityDao = new VideoEntityDao(videoEntityDaoConfig, this);
        searchItemEntityDao = new SearchItemEntityDao(searchItemEntityDaoConfig, this);
        historyItemEntityDao = new HistoryItemEntityDao(historyItemEntityDaoConfig, this);
        userItemEntityDao = new UserItemEntityDao(userItemEntityDaoConfig, this);

        registerDao(VideoEntity.class, videoEntityDao);
        registerDao(SearchItemEntity.class, searchItemEntityDao);
        registerDao(HistoryItemEntity.class, historyItemEntityDao);
        registerDao(UserItemEntity.class, userItemEntityDao);
    }
    
    public void clear() {
        videoEntityDaoConfig.clearIdentityScope();
        searchItemEntityDaoConfig.clearIdentityScope();
        historyItemEntityDaoConfig.clearIdentityScope();
        userItemEntityDaoConfig.clearIdentityScope();
    }

    public VideoEntityDao getVideoEntityDao() {
        return videoEntityDao;
    }

    public SearchItemEntityDao getSearchItemEntityDao() {
        return searchItemEntityDao;
    }

    public HistoryItemEntityDao getHistoryItemEntityDao() {
        return historyItemEntityDao;
    }

    public UserItemEntityDao getUserItemEntityDao() {
        return userItemEntityDao;
    }

}
