package com.baogetv.app.db.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORY_ITEM_ENTITY".
*/
public class HistoryItemEntityDao extends AbstractDao<HistoryItemEntity, Long> {

    public static final String TABLENAME = "HISTORY_ITEM_ENTITY";

    /**
     * Properties of entity HistoryItemEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property HistoryId = new Property(1, String.class, "historyId", false, "HISTORY_ID");
        public final static Property VideoId = new Property(2, String.class, "videoId", false, "VIDEO_ID");
        public final static Property VideoTitle = new Property(3, String.class, "videoTitle", false, "VIDEO_TITLE");
        public final static Property PicUrl = new Property(4, String.class, "picUrl", false, "PIC_URL");
        public final static Property AddTime = new Property(5, String.class, "addTime", false, "ADD_TIME");
    }


    public HistoryItemEntityDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryItemEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORY_ITEM_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"HISTORY_ID\" TEXT," + // 1: historyId
                "\"VIDEO_ID\" TEXT," + // 2: videoId
                "\"VIDEO_TITLE\" TEXT," + // 3: videoTitle
                "\"PIC_URL\" TEXT," + // 4: picUrl
                "\"ADD_TIME\" TEXT);"); // 5: addTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORY_ITEM_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HistoryItemEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String historyId = entity.getHistoryId();
        if (historyId != null) {
            stmt.bindString(2, historyId);
        }
 
        String videoId = entity.getVideoId();
        if (videoId != null) {
            stmt.bindString(3, videoId);
        }
 
        String videoTitle = entity.getVideoTitle();
        if (videoTitle != null) {
            stmt.bindString(4, videoTitle);
        }
 
        String picUrl = entity.getPicUrl();
        if (picUrl != null) {
            stmt.bindString(5, picUrl);
        }
 
        String addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindString(6, addTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HistoryItemEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String historyId = entity.getHistoryId();
        if (historyId != null) {
            stmt.bindString(2, historyId);
        }
 
        String videoId = entity.getVideoId();
        if (videoId != null) {
            stmt.bindString(3, videoId);
        }
 
        String videoTitle = entity.getVideoTitle();
        if (videoTitle != null) {
            stmt.bindString(4, videoTitle);
        }
 
        String picUrl = entity.getPicUrl();
        if (picUrl != null) {
            stmt.bindString(5, picUrl);
        }
 
        String addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindString(6, addTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HistoryItemEntity readEntity(Cursor cursor, int offset) {
        HistoryItemEntity entity = new HistoryItemEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // historyId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // videoId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // videoTitle
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // picUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // addTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HistoryItemEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHistoryId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVideoId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVideoTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPicUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HistoryItemEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HistoryItemEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HistoryItemEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
